### ISSUE TITLE
Module descriptors with """ comment not accepted

### ISSUE THREAD

**Issue by dlkw** [renatoathaydes/ceylon-gradle-plugin#12]
If I want to compile a module with module.ceylon beginning like

``` ceylon
"""
   This is etc.
"""
by("Dirk Lattermann")
module de.dlkw.asn1 "0.0.1"
```

I get

```
* What went wrong:
Execution failed for task ':resolveCeylonDependencies'.
> Cannot parse module [/home/d3/SammelDirk-060203/prj/dev-ceylon/ceylon-crypto/source/de/dlkw/asn1/module.ceylon]. Error on line 2: expected annotation or module name, found 'This'
```

Funnily, when exchanging the comment text with `some explanation`, then the message is different.

```
* What went wrong:
Execution failed for task ':resolveCeylonDependencies'.
> Cannot parse module [/home/d3/SammelDirk-060203/prj/dev-ceylon/ceylon-crypto/source/de/dlkw/asn1/module.ceylon]. Error on line 3: more than one doc String is not allowed
```

It also seems to depend on if the last char of the comment is a period.

**Comment by renatoathaydes** [comment]
You can use single double-quotes for the doc-string. Using 3 double-quotes is not supported yet.

**Comment by dlkw** [comment]
Am Fri, 17 Jun 2016 09:45:52 -0700
schrieb Renato Athaydes notifications@github.com:

> You can use single quotes for the doc-string. Using 3-quotes is not
> supported yet.

Yes, I'm getting away with his. Thank you.

**Comment by renatoathaydes** [comment]
Please use version 1.2.0 which fixes this issue.
