### ISSUE TITLE
Get this on the Gradle plugin portal?

### ISSUE THREAD

**Issue by russel** [renatoathaydes/ceylon-gradle-plugin#2]
If this plugin was available via the standard Gradle plugin portal then:

```
plugins {
    id 'com.athaydes.ceylon' version '1.0'
}
```

could be used in the Gradle build script.

**Comment by renatoathaydes** [comment]
I know about that... but I had issues with my tests in another project because of this (the declaration you suggest won't work if your plugin is only available in a local repo - ie. for testing).

**Comment by russel** [comment]
Indeed this only works for plugins deployed to the Gradle repository of plugins. No use for testing, excellent for general users.

**Comment by renatoathaydes** [comment]
Done, version 1.1 has just been released and is on the Gradle Plugin Portal.

**Comment by russel** [comment]
Works a treat. Thanks for putting the time in to make this change.
