### ISSUE TITLE
Compilation Fails When Build Path Contains Whitespace

### ISSUE THREAD

**Issue by phlopsi** [renatoathaydes/ceylon-gradle-plugin#22]
When running gradle build I get the following error:
`ceylon compile: Overrides file 'C:\Users\<partial user name, cut off at space>' does not exist`

From a quick look at the code base, I would say the origin is here: https://github.com/renatoathaydes/ceylon-gradle-plugin/blob/1.3.0-RELEASE/src/main/groovy/com/athaydes/gradle/ceylon/util/CeylonCommandOptions.groovy#L17
`options << "--overrides ${overrides.absolutePath}"`

Should probably be wrapped in quotations marks, to not fail on paths, containing whitespace.

**Comment by renatoathaydes** [comment]
The old Windows issue of whitespaces in paths :)

Feel free to make a pull request as you already found the fix for the issue!

I will release a new version soon, so this fix can get out in no time!

**Comment by renatoathaydes** [comment]
The fix has been publish with release 1.3.1.

Please confirm that it works in Windows (it works on Mac and Linux).

**Comment by phlopsi** [comment]
Can I simply import the build.gradle from the test module into IntelliJ? I tried doing that and when I execute build --debug, I get the following output: https://gist.github.com/phlopsi/7de206cf41f5310a5360bd301f8cdb49
The interesting part is probably be this:
```
16:33:01.285 [DEBUG] [com.athaydes.gradle.ceylon.util.CeylonRunner] Running Ceylon executable: C:\Users\<my name with spaces>\_\ceylon-1.3.1\bin\ceylon.bat
16:33:01.285 [INFO] [com.athaydes.gradle.ceylon.util.CeylonRunner] Running command: [C:\Users\<my name with spaces>\_\ceylon-1.3.1\bin\ceylon.bat, compile, --overrides=C:\Users\<my name with spaces>\Documents\GitHub\ceylon-gradle-plugin\ceylon-gradle-plugin-tests\module-with-whitespace-path\build\overrides.xml, --flat-classpath, --rep=aether:C:\Users\<my name with spaces>\Documents\GitHub\ceylon-gradle-plugin\ceylon-gradle-plugin-tests\module-with-whitespace-path\build\maven-settings.xml, --rep=C:\Users\<my name with spaces>\Documents\GitHub\ceylon-gradle-plugin\ceylon-gradle-plugin-tests\module-with-whitespace-path\modules, --out=C:\Users\<my name with spaces>\Documents\GitHub\ceylon-gradle-plugin\ceylon-gradle-plugin-tests\module-with-whitespace-path\modules, --source=source, --resource=test-resource, com.athaydes.simple]
16:33:01.816 [ERROR] [system.err] ceylon compile: Module com.athaydes.simple not found in source directories:
16:33:01.816 [ERROR] [system.err] source
16:33:01.816 [ERROR] [system.err] 
16:33:01.819 [ERROR] [system.err] Usage:
16:33:01.903 [ERROR] [system.err] ceylon compile [--apt=<module>...] [--auto-export-maven-dependencies] [--
16:33:01.906 [ERROR] [system.err]                cacherep=<url>] [--cwd=<dir>] [--ee] [--ee-annotation=<value>...
16:33:01.906 [ERROR] [system.err]                ] [--ee-import=<value>...] [--encoding=<encoding>] [--flat-
16:33:01.911 [ERROR] [system.err]                classpath] [--fully-export-maven-dependencies] [--generate-
16:33:01.911 [ERROR] [system.err]                module-info] [--include-dependencies[=<flags>]] [--incremental]
16:33:01.912 [ERROR] [system.err]                [--javac=<option>...] [--jdk-provider=<module>] [--maven-
16:33:01.912 [ERROR] [system.err]                overrides=<file>] [--no-default-repositories] [--no-osgi] [--no-
16:33:01.912 [ERROR] [system.err]                pom] [--offline] [--osgi-provided-bundles=<modules>] [--out=
16:33:01.914 [ERROR] [system.err]                <url>] [--overrides=<file>] [--pack200] [--pass=<secret>] [--
16:33:01.915 [ERROR] [system.err]                progress] [--rep=<url>...] [--resource=<dirs>...] [--resource-
16:33:01.919 [ERROR] [system.err]                root=<folder-name>] [--source=<dirs>...] [--src=<dirs>...] [--
16:33:01.919 [ERROR] [system.err]                suppress-warning[=<warnings>...]] [--sysrep=<url>] [--target=
16:33:01.919 [ERROR] [system.err]                <version>] [--timeout=<seconds>] [--user=<name>] [--verbose[=
16:33:01.920 [ERROR] [system.err]                <flags>]] [--] [<moduleOrFile...>]
16:33:01.921 [ERROR] [system.err] 
16:33:01.921 [ERROR] [system.err] Run 'ceylon help compile' for more help
16:33:01.935 [DEBUG] [com.athaydes.gradle.ceylon.util.CeylonRunner] Ceylon process finished with code 2
```

**Comment by renatoathaydes** [comment]
This [line](https://github.com/renatoathaydes/ceylon-gradle-plugin/blob/master/ceylon-gradle-plugin-tests/module-with-whitespace-path/build.gradle#L13
) should change the `source` parameter:

```
sourceRoots = [ "All Ceylon Sources" ]
```

Looks like something is overriding the `source` option on your side?! If you run it from the shell, it works, or at least works for me.

**Comment by phlopsi** [comment]
I ran `ceylon-gradle-plugin\ceylon-gradle-plugin-tests>gradlew :module-with-whitespace-path:testCeylon` from the console and the same error appeared. Here is how the project looks inside my IDE: [Screenshot](http://i.imgur.com/gclVrgE.png)

**Comment by renatoathaydes** [comment]
Oh.... you found a bug!

Running this works:

```
../gradlew clean :module-with-whitespace-path:compileC
```

You can use the `Pget-ceylon-command` option to confirm the Ceylon command the Gradle plugin emits  is correct:

```
../gradlew clean :module-with-whitespace-path:compileC -Pget-ceylon-command
```

But I must have changed something that broke the tests before releasing!!

Argh!! I will fix tomorrow, now it's already late here...

**Comment by renatoathaydes** [comment]
Ah, I found the issue... it's not a bug, actually :D you see, when you run tests, the plugin will use `testRoots` to compile your tests.

So you need to set that as well!

But in any case, there's no tests in this module. The test is to just compile the module! That's how I use it.

Anyway, there's no bug... it's late and I got confused... hope you agree!?

**Comment by phlopsi** [comment]
Since it only crashed when trying to run the tests and the compilation was just fine, this issue seems to be fixed.

If anything, I'd file another issue to request changing the default of `testRoots` from `"source"` to `sourceRoots`.

**Comment by renatoathaydes** [comment]
The problem is that the `testModule` property defaults to the value of `module`. But `testRoots` does not default to `sourceRoots`, it defaults to the `source` directory, as in Ceylon... this could be seen as a "bug", I guess... more expected would be if the default for `testRoots` were the same as `sourceRoots` IF `testModule` is not specified.
