### ISSUE TITLE
Using the plugin fails with gradle 3.4

### ISSUE THREAD

**Issue by andreas-schilling** [renatoathaydes/ceylon-gradle-plugin#24]
When using Gradle 3.4, the build fails with the following exception:
```
:resolveCeylonDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':resolveCeylonDependencies'.
> Resolving configuration 'apiElements' directly is not allowed
```

This is due to these changes: https://discuss.gradle.org/t/3-4-rc-1-3-3-resolving-configurations-may-be-disallowed-and-throw-illegalstateexception/21470
Some discussion can also be found here: https://github.com/jeremylong/dependency-check-gradle/issues/31

I believe it should be fairly easy to solve. If I find some time I maybe can look into it, but wanted to report it nevertheless.
I believe the problem is in `DependencyTree.groovy`, method `directDependenciesOf()` (the call to `.resolvedConfiguration`)

**Comment by renatoathaydes** [comment]
Would be nice if you could figure out how to fix that... hope it's not too much trouble to use older Gradle versions for now. Most new versions add nothing to JVM projects.

**Comment by andreas-schilling** [comment]
No, no trouble at all using 3.3. it's just my habit of going latest&greatest all the time :-)
As said, will try to find some time to look into it.
