### ISSUE TITLE
Publish latest fixes in new patch release of plugin

### ISSUE THREAD

**Issue by lucono** [renatoathaydes/ceylon-gradle-plugin#6]
This is a great plugin.

Any chance of publishing the latest fixes (specifically [this fix](https://github.com/renatoathaydes/ceylon-gradle-plugin/commit/a632a83edac9972d1f2f70dab337a6c427002b24) and [this one](https://github.com/renatoathaydes/ceylon-gradle-plugin/commit/9ad888ea41bad2afc028a9653f660b5d0295945a)) in a new patch release? These resolved the only two issues I experienced with the plugin.

**Comment by renatoathaydes** [comment]
I was hoping to add more improvements to make a release, but I guess these are pretty good improvements already for a minor release... will do.

**Comment by renatoathaydes** [comment]
Published version 1.1.1 with latest fixes.

**Comment by lucono** [comment]
Great, thanks.
