### ISSUE TITLE
ceylon plugin should tap into common build/test lifecycle

### ISSUE THREAD

**Issue by luolong** [renatoathaydes/ceylon-gradle-plugin#9]
Currently, Ceylon plugin declares it's own set of tasks: ceylonCompile, ceylonTest, etc.

As a Gradle user, I found it somewhat strange that Ceylon targets did not tap into the more common gradle byuld lifecycle -- calling `./gradlew build` did absolutely nothing.

**Comment by russel** [comment]
On the up side "gradle test" does connect to "gradle ceylonTest". Having said this, I agree that the Ceylong plugin should harmonize with the standard Gradle lifecycle nomenclature.

**Comment by renatoathaydes** [comment]
Do you have a reference I can use to know what is considered the standard Gradle lifecycle?

[This](https://docs.gradle.org/current/userguide/build_lifecycle.html) does not seem to help.

**Comment by luolong** [comment]
For a Java developer, I guess, this is it: https://docs.gradle.org/current/userguide/java_plugin.html#N15009

**Comment by luolong** [comment]
This is of course in case you build with Java/for java. I guess detecting if java plugin has been applied first is proper way to do it...

**Comment by russel** [comment]
@renatoathaydes The terminology here gets a wee bit weird sadly: target, task, lifecycle, etc. all have Ant, Maven, Gant, Gradle overtones. Moreover Gradle is introducing a new software model that will evolve things.

We must not brew up a storm in a teacup, as I think there is less of a problem here than we might imagine.

The tasks ceylonCompile and ceylonTest almost certainly need renaming compileCeylon and compileTestCeylon and made subtasks of classes and testClasses. The idea here is to fit in with the standard Java, Groovy, Scala, Kotlin plugin lifecycles so as to provide no surprises, especially when mixing Java and Ceylon code.

**Comment by russel** [comment]
I'll clone the repository and take a look. Hopefully I can create a pull request rather than just make comment.

**Comment by luolong** [comment]
Eh @russel, you beat me to it :)
(I'll clone the repo regardless ... might have some PRs coming up as I give this plugin a serious ride)

**Comment by renatoathaydes** [comment]
> The tasks ceylonCompile and ceylonTest ...

@russel  there's no such tasks... they are called `compileCeylon` and `testCeylon` respectively :)

Anyway, I followed quite similar names with the Groovy and the Java plugin. Just didn't bother with `build` and `check` as I'm not used to using them myself.

To do this properly, we need to see whether the other plugins (Java, Groovy etc) check if a task exists with a certain name and just try to extend it in case it does... or if it will mindlessly break if I add a task with the name they want to use and it just happens that the `ceylon` plugin gets applied before the others....

I welcome help with this, but please make sure all the test projects continue to work with any changes you might want to make.

**Comment by renatoathaydes** [comment]
Side note: @russel  it works when you do `gradle test` because Gradle cannot see ambiguity with any other tasks in the project, so it knows to call `testCeylon`... you could just type `gradle tC` and it would work as well (capitalized letters are considered by Gradle, similar to how IntelliJ allows you to search by the first letters of each word in a method/class).

**Comment by luolong** [comment]
Looking at the Gradle API docs, [JavaCompile task](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/compile/JavaCompile.html) inherits from `AbstractCompile` task, as do `AbstractScalaCompile` and `GrrovyCompile` tasks.

Maybe it's enough to follow the inheritance hierarchy to get the desired behavior?

**Comment by luolong** [comment]
Also, browsing the API, I found this package: [org.gradle.language.base.plugins](https://docs.gradle.org/current/javadoc/org/gradle/language/base/plugins/package-summary.html)

**Comment by renatoathaydes** [comment]
Implemented the lifecycle tasks as explained in [Table 45.3](https://docs.gradle.org/current/userguide/java_plugin.html#N15056).

**Comment by gavinking** [comment]
@renatoathaydes Great! Thanks!

**Comment by renatoathaydes** [comment]
Released version 1.2.0 that fixes this issue.

Notice that if you apply the `java` plugin (or other language), you need to apply that first, then the Ceylon plugin. The other plugins don't seem to check if the default stuff was already added to the project, but this plugin does.
